"""Add churn forensics

Revision ID: 12be2bfca678
Revises: 1d7cbfd3871e
Create Date: 2026-06-17 19:46:21.459573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12be2bfca678'
down_revision: Union[str, Sequence[str], None] = '1d7cbfd3871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_forensics_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('churn_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emotion_trajectory', sa.JSON(), nullable=True),
    sa.Column('contagion_context', sa.JSON(), nullable=True),
    sa.Column('counterfactual_history', sa.JSON(), nullable=True),
    sa.Column('economic_priority_history', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=64), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_churn_forensics_tenant_customer', 'churn_forensics_reports', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_churn_forensics_verdict', 'churn_forensics_reports', ['tenant_id', 'verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_churn_forensics_verdict', table_name='churn_forensics_reports')
    op.drop_index('ix_churn_forensics_tenant_customer', table_name='churn_forensics_reports')
    op.drop_table('churn_forensics_reports')
    # ### end Alembic commands ###
