"""Add agent session

Revision ID: 1d7cbfd3871e
Revises: 5fe56d2e5988
Create Date: 2026-06-17 19:41:37.132918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7cbfd3871e'
down_revision: Union[str, Sequence[str], None] = '5fe56d2e5988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'action_type', name='uq_agent_action_type')
    )
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_agent_sessions_tenant', 'agent_sessions', ['tenant_id'], unique=False)
    op.create_table('agent_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_action_logs_tenant', 'agent_action_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_action_logs_tenant', table_name='agent_action_logs')
    op.drop_table('agent_action_logs')
    op.drop_index('ix_agent_sessions_tenant', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('agent_action_registry')
    # ### end Alembic commands ###
