"""Initial schema

Revision ID: 390f23826c00
Revises: 
Create Date: 2026-06-16 12:27:21.425722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390f23826c00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('data_residency_region', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_audit_tenant_action', 'audit_logs', ['tenant_id', 'action_type'], unique=False)
    op.create_index('ix_audit_tenant_date', 'audit_logs', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('campaign_queue',
    sa.Column('queue_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_type', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('generated_email_subject', sa.String(length=512), nullable=True),
    sa.Column('generated_email_body', sa.Text(), nullable=True),
    sa.Column('shap_context', sa.JSON(), nullable=True),
    sa.Column('churn_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_approve_after_hours', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index('ix_campaign_queue_created', 'campaign_queue', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_campaign_queue_tenant_status', 'campaign_queue', ['tenant_id', 'status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('recency_days', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('monetary_value', sa.Float(), nullable=False),
    sa.Column('session_failures', sa.Integer(), nullable=False),
    sa.Column('payment_friction_index', sa.Float(), nullable=False),
    sa.Column('active_support_tickets', sa.Integer(), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'user_id', name='uq_customer_merchant_user')
    )
    op.create_index('ix_customer_deleted', 'customers', ['merchant_id', 'is_deleted'], unique=False)
    op.create_index('ix_customer_merchant_churn', 'customers', ['merchant_id', 'churn_probability'], unique=False)
    op.create_index('ix_customer_merchant_segment', 'customers', ['merchant_id', 'segment'], unique=False)
    op.create_table('drift_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('psi_score', sa.Float(), nullable=True),
    sa.Column('js_divergence', sa.Float(), nullable=True),
    sa.Column('drift_level', sa.String(length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_drift_tenant_date', 'drift_logs', ['tenant_id', 'evaluated_at'], unique=False)
    op.create_index('ix_drift_tenant_feature', 'drift_logs', ['tenant_id', 'feature_name'], unique=False)
    op.create_table('erasure_certificates',
    sa.Column('erasure_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id_hash', sa.String(length=64), nullable=False),
    sa.Column('tables_cleared', sa.JSON(), nullable=False),
    sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('certificate_pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('erasure_id')
    )
    op.create_table('experiment_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_a_count', sa.Integer(), nullable=False),
    sa.Column('group_b_count', sa.Integer(), nullable=False),
    sa.Column('group_a_retained', sa.Integer(), nullable=False),
    sa.Column('group_b_retained', sa.Integer(), nullable=False),
    sa.Column('chi_squared_stat', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('winning_group', sa.String(length=1), nullable=True),
    sa.Column('auto_promoted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index('ix_registry_tenant_active', 'model_registry', ['tenant_id', 'is_active'], unique=False)
    op.create_table('shap_values',
    sa.Column('shap_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('shap_id')
    )
    op.create_index('ix_shap_computed_at', 'shap_values', ['tenant_id', 'computed_at'], unique=False)
    op.create_index('ix_shap_tenant_customer', 'shap_values', ['tenant_id', 'customer_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pii_fields', sa.JSON(), nullable=True),
    sa.Column('data_residency_region', sa.String(length=8), nullable=True),
    sa.Column('campaign_auto_approve_hours', sa.Integer(), nullable=True),
    sa.Column('digest_email_enabled', sa.Boolean(), nullable=True),
    sa.Column('digest_recipients', sa.JSON(), nullable=True),
    sa.Column('churn_threshold', sa.Float(), nullable=True),
    sa.Column('active_template', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_integrations',
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('integration_name', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('integration_id'),
    sa.UniqueConstraint('tenant_id', 'integration_name', name='uq_integration_tenant_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index('ix_user_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('webhook_delivery_logs',
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index('ix_webhook_tenant_event', 'webhook_delivery_logs', ['tenant_id', 'event_type'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_apikey_tenant_revoked', 'api_keys', ['tenant_id', 'is_revoked'], unique=False)
    op.create_table('campaign_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_queue.queue_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_campaign_event_tenant', 'campaign_events', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_campaign_event_type', 'campaign_events', ['tenant_id', 'event_type'], unique=False)
    op.create_table('customer_preferences',
    sa.Column('pref_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('preferred_channel', sa.String(length=16), nullable=True),
    sa.Column('email_optout', sa.Boolean(), nullable=True),
    sa.Column('sms_optout', sa.Boolean(), nullable=True),
    sa.Column('push_optout', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('pref_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_merchant_ts', 'event_logs', ['merchant_id', 'timestamp'], unique=False)
    op.create_index('ix_event_merchant_type', 'event_logs', ['merchant_id', 'event_type'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=1), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_clicked', sa.Boolean(), nullable=True),
    sa.Column('churned_after_7d', sa.Boolean(), nullable=True),
    sa.Column('churned_after_30d', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index('ix_exp_assigned_at', 'experiment_assignments', ['tenant_id', 'assigned_at'], unique=False)
    op.create_index('ix_exp_tenant_group', 'experiment_assignments', ['tenant_id', 'group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exp_tenant_group', table_name='experiment_assignments')
    op.drop_index('ix_exp_assigned_at', table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index('ix_event_merchant_type', table_name='event_logs')
    op.drop_index('ix_event_merchant_ts', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('customer_preferences')
    op.drop_index('ix_campaign_event_type', table_name='campaign_events')
    op.drop_index('ix_campaign_event_tenant', table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index('ix_apikey_tenant_revoked', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_webhook_tenant_event', table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_index('ix_user_tenant_role', table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_integrations')
    op.drop_table('tenant_configs')
    op.drop_index('ix_shap_tenant_customer', table_name='shap_values')
    op.drop_index('ix_shap_computed_at', table_name='shap_values')
    op.drop_table('shap_values')
    op.drop_index('ix_registry_tenant_active', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_table('experiment_results')
    op.drop_table('erasure_certificates')
    op.drop_index('ix_drift_tenant_feature', table_name='drift_logs')
    op.drop_index('ix_drift_tenant_date', table_name='drift_logs')
    op.drop_table('drift_logs')
    op.drop_index('ix_customer_merchant_segment', table_name='customers')
    op.drop_index('ix_customer_merchant_churn', table_name='customers')
    op.drop_index('ix_customer_deleted', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_campaign_queue_tenant_status', table_name='campaign_queue')
    op.drop_index('ix_campaign_queue_created', table_name='campaign_queue')
    op.drop_table('campaign_queue')
    op.drop_index('ix_audit_tenant_date', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('merchants')
    # ### end Alembic commands ###
