"""Add InterventionExperiment

Revision ID: 652776e19373
Revises: 390f23826c00
Create Date: 2026-06-16 12:56:50.043491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652776e19373'
down_revision: Union[str, Sequence[str], None] = '390f23826c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_experiments',
    sa.Column('intervention_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('action_taken', sa.String(length=128), nullable=False),
    sa.Column('causal_uplift_predicted', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_queue.queue_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_index('ix_intervention_tenant_status', 'intervention_experiments', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intervention_tenant_status', table_name='intervention_experiments')
    op.drop_table('intervention_experiments')
    # ### end Alembic commands ###
