"""Add CustomerEdge and enable_inferred_edges

Revision ID: b70af9358edf
Revises: 652776e19373
Create Date: 2026-06-17 18:30:31.175964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70af9358edf'
down_revision: Union[str, Sequence[str], None] = '652776e19373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_customer_id', sa.String(length=64), nullable=False),
    sa.Column('target_customer_id', sa.String(length=64), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('inference_basis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_customer_id', 'target_customer_id', name='uq_customer_edge')
    )
    op.create_index('ix_customer_edges_tenant_source', 'customer_edges', ['tenant_id', 'source_customer_id'], unique=False)
    op.create_index('ix_customer_edges_tenant_target', 'customer_edges', ['tenant_id', 'target_customer_id'], unique=False)
    op.add_column('tenant_configs', sa.Column('enable_inferred_edges', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_configs', 'enable_inferred_edges')
    op.drop_index('ix_customer_edges_tenant_target', table_name='customer_edges')
    op.drop_index('ix_customer_edges_tenant_source', table_name='customer_edges')
    op.drop_table('customer_edges')
    # ### end Alembic commands ###
