"""Add counterfactual paths

Revision ID: d4cb79386a95
Revises: 12be2bfca678
Create Date: 2026-06-17 20:25:37.619362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cb79386a95'
down_revision: Union[str, Sequence[str], None] = '12be2bfca678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterfactual_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('intervention_type', sa.String(length=64), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('predicted_risk_reduction', sa.Float(), nullable=False),
    sa.Column('roi_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counterfactual_paths')
    # ### end Alembic commands ###
