"""
components/tab_forensics.py — Post-Mortem Churn Forensics
==========================================================
"""

import streamlit as st
import pandas as pd
import requests
import os
import altair as alt

API_BASE = os.getenv("API_BASE", "http://localhost:8000")

def render(tenant_id: int):
    st.header("Churn Forensics (Post-Mortem)")
    st.markdown("Autogenerated post-mortem reports proving whether the platform could have prevented recent churns.")
    
    headers = {"Authorization": f"Bearer {st.session_state.get('token', '')}"}
    
    # Check if TENANT_ADMIN to show summary
    role = st.session_state.get("role", "")
    if role in ("SUPER_ADMIN", "TENANT_ADMIN"):
        try:
            sum_resp = requests.get(f"{API_BASE}/api/v1/forensics/summary", headers=headers)
            if sum_resp.status_code == 200:
                summary = sum_resp.json()
                total = summary.get("total", 0)
                if total > 0:
                    st.subheader(f"Tenant-Wide Aggregate ({total} Recent Churns)")
                    st.markdown("> **What fraction of churns had a viable intervention available that wasn't taken?**")
                    cols = st.columns(len(summary["breakdown"]))
                    for i, (k, v) in enumerate(summary["breakdown"].items()):
                        pct = summary["percentages"][k]
                        cols[i].metric(k.replace("_", " ").title(), f"{v} ({pct}%)")
                    st.divider()
        except Exception as e:
            st.error(f"Failed to fetch summary: {e}")

    st.divider()
    st.subheader("Semantic Insights (RAG)")
    st.markdown("Use Gemini to analyze unstructured support tickets from recently churned users to find hidden themes.")
    st.markdown("<br>", unsafe_allow_html=True)
    col_rag_btn, _ = st.columns([1, 2])
    with col_rag_btn:
        analyze_btn = st.button("Analyze Support Tickets", help="Performs a Retrieval-Augmented Generation (RAG) scan across thousands of recent support tickets to discover hidden, recurring themes that are causing users to churn.")
        
    if analyze_btn:
        with st.spinner("Extracting themes from Vector DB..."):
            try:
                rag_resp = requests.get(f"{API_BASE}/api/v1/forensics/semantic_insights", headers=headers)
                if rag_resp.status_code == 200:
                    insights = rag_resp.json().get("insights", [])
                    if not insights:
                        st.info("No insights found.")
                    else:
                        for i, ins in enumerate(insights):
                            color = "red" if ins['severity'].lower() == 'critical' else "orange" if ins['severity'].lower() == 'high' else "blue"
                            st.markdown(f"**<span style='color:{color}'>{ins['severity'].upper()}</span> | {ins['theme']} ({ins['percentage']})**", unsafe_allow_html=True)
                            st.write(ins['description'])
                else:
                    st.error("Failed to load insights.")
            except Exception as e:
                st.error(f"Error: {e}")
    st.divider()

    # List recent reports
    try:
        list_resp = requests.get(f"{API_BASE}/api/v1/forensics/", headers=headers)
        if list_resp.status_code == 200:
            reports = list_resp.json().get("reports", [])
            if not reports:
                st.info("No churn forensics reports generated yet.")
                
                # Setup demo functionality
                st.markdown("---")
                mock_customers = ["5482-NUPNA", "cust_123", "8472-ABC", "1192-XYZ", "9941-RPO", "7712-QWE"]
                col_sel, col_btn = st.columns([1, 2])
                with col_sel:
                    demo_cust = st.selectbox("Customer ID to trigger manual report generation:", options=mock_customers)
                with col_btn:
                    st.markdown("<div style='margin-top: 28px;'></div>", unsafe_allow_html=True)
                    gen_btn = st.button("Generate Demo Forensics Report")
                    
                if gen_btn:
                    with st.spinner("Compiling cross-module history..."):
                        resp = requests.post(f"{API_BASE}/api/v1/forensics/{demo_cust}/generate", headers=headers)
                        if resp.status_code == 200:
                            st.success("Report generated!")
                            st.rerun()
                        else:
                            st.error("Failed to generate report (does the customer exist?)")
            else:
                st.subheader("Individual Customer Reports")
                for r in reports:
                    color = "red" if r['verdict'] == "INTERVENTION_AVAILABLE_NOT_TAKEN" else "orange" if r['verdict'] == "INTERVENTION_TAKEN_BUT_FAILED" else "gray"
                    with st.expander(f"Customer {r['customer_id']} | Verdict: {r['verdict']}"):
                        st.markdown(f"**Reasoning:** {r['reasoning']}")
                        
                        col1, col2 = st.columns(2)
                        with col1:
                            st.markdown("#### Emotion Trajectory (30 days prior)")
                            if r.get("emotion_trajectory"):
                                df_em = pd.DataFrame(r["emotion_trajectory"])
                                chart = alt.Chart(df_em).mark_line(point=True).encode(
                                    x='day',
                                    y='risk_score',
                                    tooltip=['day', 'risk_score', 'sentiment']
                                ).properties(height=200)
                                st.altair_chart(chart, use_container_width=True)
                            else:
                                st.write("No emotion data.")
                                
                        with col2:
                            st.markdown("#### Contagion Graph Context")
                            contagion = r.get("contagion_context", {})
                            if contagion:
                                st.write(f"- Direct connections: {contagion.get('direct_connections', 0)}")
                                st.write(f"- Is Influencer: {contagion.get('is_influencer', False)}")
                                st.write(f"- Total weight at risk: {contagion.get('total_weight_at_risk', 0.0)}")
                            else:
                                st.write("No contagion data.")
                        
                        st.markdown("#### Counterfactual Timeline & Interventions")
                        cfs = r.get("counterfactual_history", [])
                        if cfs:
                            st.dataframe(pd.DataFrame(cfs), use_container_width=True)
                        else:
                            st.write("No viable counterfactual paths were identified prior to churn.")
                            
                        st.markdown("#### Economic Priority Context")
                        eco = r.get("economic_priority_history", [])
                        if eco:
                            st.dataframe(pd.DataFrame(eco), use_container_width=True)
        else:
            st.error("Failed to fetch reports list.")
    except Exception as e:
        st.error(f"Error communicating with backend: {e}")
