"""initial_schema_v3

Revision ID: a7d554641b95
Revises: 
Create Date: 2026-06-12 15:04:11.251307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d554641b95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('recency_days', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('monetary_value', sa.Float(), nullable=False),
    sa.Column('session_failures', sa.Integer(), nullable=False),
    sa.Column('payment_friction_index', sa.Float(), nullable=False),
    sa.Column('active_support_tickets', sa.Integer(), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'user_id', name='uq_customer_merchant_user')
    )
    op.create_index('ix_customer_deleted', 'customers', ['merchant_id', 'is_deleted'], unique=False)
    op.create_index('ix_customer_merchant_churn', 'customers', ['merchant_id', 'churn_probability'], unique=False)
    op.create_index('ix_customer_merchant_segment', 'customers', ['merchant_id', 'segment'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_merchant_ts', 'event_logs', ['merchant_id', 'timestamp'], unique=False)
    op.create_index('ix_event_merchant_type', 'event_logs', ['merchant_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_merchant_type', table_name='event_logs')
    op.drop_index('ix_event_merchant_ts', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_customer_merchant_segment', table_name='customers')
    op.drop_index('ix_customer_merchant_churn', table_name='customers')
    op.drop_index('ix_customer_deleted', table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    op.drop_table('merchants')
    # ### end Alembic commands ###
